config/routes.rb
Rails.application.routes.draw do
  root 'fields#index'

  resources :fields
end

app/models/field.rb
class Field < ActiveRecord::Base
  validates :name, presence: true

  def self.proper_geometry(shape)
    return true if shape.empty? || JSON.parse(shape)['coordinates'].empty?
    wkt_shape = self.get_wkt(shape)
    sql = "SELECT ST_IsValid(ST_GeomFromText('#{wkt_shape}'))"
    sql_reason = "SELECT ST_IsValidReason(ST_GeomFromText('#{wkt_shape}'))"
    result = ActiveRecord::Base.connection.execute(sql)
    reason = ActiveRecord::Base.connection.execute(sql_reason)
    if result.getvalue(0,0) == 'f'
      begin
      raise reason.getvalue(0,0)
      rescue Exception => e
        exception = e.message
      end
      exception
    else
      true
    end
  end

  def self.get_wkt(value)
    JSON.parse(value)['coordinates'].to_wkt_multi_polygon
  end

  def self.to_geographic(shape)
    self.load_factory.multi_polygon(RGeo::GeoJSON.decode(shape, :json_parser => :json))
  end

  def shape_to_json_geo
    RGeo::GeoJSON.encode(self.shape).to_json.html_safe
  end

  def self.load_multipolygon_arr
    arr = []
    self.all.each do |field|
      shape = RGeo::GeoJSON.encode(field.shape)
      arr << shape
    end
    arr.to_json.html_safe
  end

  def self.load_factory
    RGeo::Geographic.spherical_factory(:srid => 4326)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :load_field, only: [:show, :edit, :update, :destroy]
  before_action :validate_and_load_shape, only: [:create, :update]

  def index
    @fields = Field.all
    @geo_data = Field.load_multipolygon_arr
  end

  def new
    @field = Field.new
  end

  def create
    @field = Field.new(name: field_params[:name], shape: @shape)

    if @field.save
      redirect_to @field, notice: 'Field was successfully created.'
    else
      render :new
    end
  end

  def show
    @geo_data = @field.shape_to_json_geo
  end

  def edit
    @field.shape = @field.shape_to_json_geo
  end

  def update
    @shape ||= @field.shape
    if @field.update(name: field_params[:name], shape: @shape)
      @field.errors.add(:invalid_geometry, @exception) unless @exception.nil?
      respond_to do |format|
        format.html { redirect_to field_path, notice: 'Field was successfully updated.' }
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @field.destroy
    redirect_to root_path, notice: 'Field was successfully destroyed.'
  end

  private

    def load_field
      @field = Field.find(params[:id])
    end

    def validate_and_load_shape
      result = Field.proper_geometry(field_params[:shape])
      if result == true
        @shape = Field.to_geographic(field_params[:shape])
      else
        @exception = result
      end
    end

    def field_params
      params.require(:field).permit(:name, :shape)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fields/_form.html.haml
.row
  = form_for @field do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :shape
      = f.text_area :shape, class: 'form-control', rows: 5
    .form-group
      = f.submit  nil, class: 'btn btn-primary'

app/views/fields/_map.html.erb
<script>
    var map = L.map('map').setView([43.1249, 1.254], 13);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        maxZoom: 18,
        id: 'grbro.128f9cf3',
        accessToken: 'pk.eyJ1IjoiZ3Jicm8iLCJhIjoiZmM0OWRhM2U2ZDZmMjA3MjkxNjc2YmQyOWE0ZGIzNWQifQ.0UeJF5ZVjBi3TK8CKp1EpQ'
    }).addTo(map);

    var drawnItems = new L.featureGroup();
    map.addLayer(drawnItems);

    var geojsonFeature = <%= @geo_data %>;
    var coordinates = geojsonFeature == null ? [] : geojsonFeature.coordinates;

    var polygonArr = [];
    coordinates.forEach(function(item, i, arr) {
        polygonArr.push({
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": item
            }
        });
    });

    var polygon = L.geoJson(polygonArr, {
        onEachFeature: function(feature, layer) {
            drawnItems.addLayer(layer);
        }
    }).addTo(map);

    var drawControl = new L.Control.Draw({
        draw: {
            polyline: false,
            rectangle: false,
            circle: false,
            marker: false
        },
        edit: {
            featureGroup: drawnItems
        }
    });
    map.addControl(drawControl);

    map.on('draw:created', function (e) {
        var layer = e.layer;
        drawnItems.addLayer(layer);
        saveLayers(drawnItems);
    });

    map.on('draw:edited', function () {
        saveLayers(drawnItems);
    });

    map.on('draw:deleted', function () {
        saveLayers(drawnItems);
    });

    var getCoords = function(drawnItems) {
        var coords = [];
        drawnItems.eachLayer(function(layer) {
            value = layer.toGeoJSON();
            coords.push(value.geometry.coordinates);
        });
        return coords;
    };

    var getMultiPolygon = function(shapes) {
        return {
            "type": "Feature",
            "geometry": {
                "type": "MultiPolygon",
                "coordinates": shapes
            }
        };
    };

    var saveLayers = function(drawnItems) {
        var shapes = getCoords(drawnItems);
        var mp = getMultiPolygon(shapes);

        $.ajax({
            method: "PATCH",
            url: "/fields/<%= @field.id %>",
            data: {'field[shape]': JSON.stringify(mp.geometry), 'field[name]': "<%= @field.name %>"},
            dataType: "script",
            success: processSuccess,
            error: processError
        });
    };

    var processSuccess = function(data) {
        if (data.status === 'ok') {
            console.log('Just posted some valid GeoJSON!');
        } else if (data.status === 'error') {
            console.log('There was a problem with GeoJSON: ' + data.message);
        }
    }

    var processError = function() {
        console.log('There was a problem with ajax.');
    }
</script>

app/views/fields/_map_index.html.erb
<script>
    var map = L.map('map').setView([43.1249, 1.254], 13);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        maxZoom: 18,
        id: 'grbro.128f9cf3',
        accessToken: 'pk.eyJ1IjoiZ3Jicm8iLCJhIjoiZmM0OWRhM2U2ZDZmMjA3MjkxNjc2YmQyOWE0ZGIzNWQifQ.0UeJF5ZVjBi3TK8CKp1EpQ'
    }).addTo(map);

    var drawnItems = new L.featureGroup();
    map.addLayer(drawnItems);

    var geojsonItems = <%= @geo_data %>;
    geojsonItems.forEach(function(geojsonFeature, i, arr) {
        var coordinates = geojsonFeature == null ? [] : geojsonFeature.coordinates;

        var polygonArr = [];
        coordinates.forEach(function(item, i, arr) {
            polygonArr.push({
                "type": "Feature",
                "geometry": {
                    "type": "Polygon",
                    "coordinates": item
                }
            });
        });

        var polygon = L.geoJson(polygonArr, {
            onEachFeature: function(feature, layer) {
                drawnItems.addLayer(layer);
            }
        }).addTo(map);
    });
</script>

app/views/fields/_shape.html.haml
Shape: #{@field.shape}

app/views/fields/create.html.haml
%h1 Fields#create
%p Find me in app/views/fields/create.html.haml

app/views/fields/edit.html.haml
= render 'form'

app/views/fields/index.html.haml
.row
  .col-md-12
    #map
      = render 'map_index'
%hr
.row
  .col-md-12
    - @fields.each do |field|
      .container-fluid
        .col-md-10
          %h4= link_to field.name, field_path(field)
        .col-md-2.text-center
          = link_to 'Edit', edit_field_path(field), class: 'btn btn-xs btn-primary'
          = link_to 'Delete', field, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
      %hr

app/views/fields/new.html.haml
= render 'form'

app/views/fields/show.html.haml
.row
  .col-md-10
    %h4 Name: #{@field.name}
  .col-md-2.text-center
    = link_to 'Edit', edit_field_path(@field), class: 'btn btn-xs btn-primary'
    = link_to 'Delete', @field, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger'
  .col-md-12
    %h5.shape
      = render 'shape'
    %h5.errors.text-danger
    #map
      = render 'map'

app/views/fields/update.js.erb
<% if @field.errors.present? %>
    <% @field.errors.full_messages.each do |message| %>
        $('.errors').html('<%= j message %>');
        $('.shape').html('<%= j render 'fields/shape' %>');
    <% end %>
<% else %>
    $('.shape').html('<%= j render 'fields/shape' %>');
    $('.errors').html('');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<section class="container">
  <section class="col-md-12">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Brand', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to('Add new field', new_field_path)  %>
            </li>
          </ul>
        </div>

      </div>
    </nav>
    <% flash.each do |name, msg| %>
        <script>
            setTimeout(function(){
                $('#flash-notice').slideUp();
            }, 1500);
        </script>
        <div id="flash-notice" class='alert alert-<%= name == "notice" ? "success" : "error" %>'>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= msg %>
        </div>
    <% end %>

    <section class="col-md-12">
      <%= yield %>
    </section>

  </section>
</section>

</body>
</html>